In [36]:
import torch
import torchvision

In [4]:
!pip install torchvision

   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   -- ------------------------------------- 0.1/1.2 MB 1.7 MB/s eta 0:00:01
   ---- ----------------------------------- 0.1/1.2 MB 2.1 MB/s eta 0:00:01
   ----- ---------------------------------- 0.2/1.2 MB 1.3 MB/s eta 0:00:01
   ----- ---------------------------------- 0.2/1.2 MB 1.3 MB/s eta 0:00:01
   ----- ---------------------------------- 0.2/1.2 MB 1.3 MB/s eta 0:00:01
   ------ --------------------------------- 0.2/1.2 MB 831.5 kB/s eta 0:00:02
   ------- -------------------------------- 0.2/1.2 MB 811.5 kB/s eta 0:00:02
   ------- -------------------------------- 0.2/1.2 MB 811.5 kB/s eta 0:00:02
   ------- -------------------------------- 0.2/1.2 MB 686.8 kB/s eta 0:00:02
   --------- ------------------------------ 0.3/1.2 MB 681.0 kB/s eta 0:00:02
   --------- ------------------------------ 0.3/1.2 MB 681.0 kB/s eta 0:00:02
   ---------- ----------------------------- 0.3/1.2 MB 656.4 kB/s eta 0:00:02
   --

  You can safely remove it manually.


   -------- ------------------------------ 34.6/159.8 MB 424.0 kB/s eta 0:04:56
   -------- ------------------------------ 34.6/159.8 MB 423.2 kB/s eta 0:04:56
   -------- ------------------------------ 34.6/159.8 MB 423.5 kB/s eta 0:04:56
   -------- ------------------------------ 34.6/159.8 MB 422.9 kB/s eta 0:04:56
   -------- ------------------------------ 34.7/159.8 MB 423.5 kB/s eta 0:04:56
   -------- ------------------------------ 34.7/159.8 MB 423.2 kB/s eta 0:04:56
   -------- ------------------------------ 34.7/159.8 MB 422.7 kB/s eta 0:04:56
   -------- ------------------------------ 34.7/159.8 MB 423.8 kB/s eta 0:04:56
   -------- ------------------------------ 34.7/159.8 MB 423.2 kB/s eta 0:04:56
   -------- ------------------------------ 34.8/159.8 MB 424.0 kB/s eta 0:04:55
   -------- ------------------------------ 34.8/159.8 MB 423.8 kB/s eta 0:04:56
   -------- ------------------------------ 34.8/159.8 MB 424.6 kB/s eta 0:04:55
   -------- ----------------------------

In [38]:
!python run.py --image_name 009835

iou co sai khong: 0.145728
1
[0. 0. 0. ... 0. 0. 0.]
(25088,)
21027
while terminal step:1
iou co sai khong: 0.1909502840002553
1
[0. 0. 0. ... 0. 0. 0.]
(25088,)
21273
while terminal step:2
iou co sai khong: 0.15325543223385962
2
[0. 0. 0. ... 0. 0. 0.]
(25088,)
21316
while terminal step:3
iou co sai khong: 0.1987720887796286
3
[0. 0. 0. ... 0. 0. 0.]
(25088,)
20975
while terminal step:4
iou co sai khong: 0.25573731737488564
3
[0. 0. 0. ... 0. 0. 0.]
(25088,)
20854
while terminal step:5
iou co sai khong: 0.32575480777654975
4
[0. 0. 0. ... 0. 0. 0.]
(25088,)
20861
while terminal step:6
iou co sai khong: 0.23930635373733694
1
[0. 0. 0. ... 0. 0. 0.]
(25088,)
21281
while terminal step:7
iou co sai khong: 0.16053824966915545
0
[0. 0. 0. ... 0. 0. 0.]
(25088,)
21086
while terminal step:8
iou co sai khong: 0.2039157870755838
5
[0. 0. 0. ... 0. 0. 0.]
(25088,)
21086
while terminal step:8
iou co sai khong: 0.2039157870755838
4
[0. 0. 0. ... 0. 0. 0.]
(25088,)
20890
while terminal step:9
iou c

c:\Users\21520\anaconda3\.conda\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\21520\anaconda3\.conda\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [40]:
!python run.py 

KeyboardInterrupt: 

In [3]:
!python run.py --image_name 009835 

iou co sai khong: 0.145728
4
[0. 0. 0. ... 0. 0. 0.]
(25088,)
20804
while terminal step:1
iou co sai khong: 0.259072
1
[0. 0. 0. ... 0. 0. 0.]
(25088,)
20815
while terminal step:2
iou co sai khong: 0.28858059375191547
5
[0. 0. 0. ... 0. 0. 0.]
(25088,)
20696
while terminal step:2
iou co sai khong: 0.28858059375191547
5
[0. 0. 0. ... 0. 0. 0.]
(25088,)
20696
while terminal step:2
iou co sai khong: 0.28858059375191547
5
[0. 0. 0. ... 0. 0. 0.]
(25088,)
20696
while terminal step:2
iou co sai khong: 0.28858059375191547
0
[0. 0. 0. ... 0. 0. 0.]
(25088,)
20997
while terminal step:3
iou co sai khong: 0.31752548222178034
0
[0. 0. 0. ... 0. 0. 0.]
(25088,)
21093
while terminal step:4
iou co sai khong: 0.2789009985970435
3
[0. 0. 0. ... 0. 0. 0.]
(25088,)
21162
while terminal step:5
iou co sai khong: 0.3477928910898857
2
[0. 0. 0. ... 0. 0. 0.]
(25088,)
20668
while terminal step:6
iou co sai khong: 0.4268753996342454
1
[0. 0. 0. ... 0. 0. 0.]
(25088,)
20913
while terminal step:7
iou co sai khon

c:\Users\21520\anaconda3\.conda\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\21520\anaconda3\.conda\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [21]:
import os
import numpy as np
from PIL import Image
import torch

In [22]:
import run

In [48]:
path_voc_test = r"e:\msrlOB-1\archive (4)\VOCtest_06-Nov-2007\VOC2007"

In [8]:
import torch
import torchvision
from models.Q_net import Q_zoom, Q_refine
from data import load_images_names_in_data_set, get_bb_of_gt_from_pascal_xml_annotation
import torchvision.transforms as T
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import argparse
import os
from PIL import Image, ImageDraw
from utils import cal_iou, reward_func
import time

# hyper-parameters
BATCH_SIZE = 100
LR = 1e-6
GAMMA = 0.9
MEMORY_CAPACITY = 1000
Q_NETWORK_ITERATION = 100
epochs = 500
NUM_ACTIONS = 6
his_actions = 4
subscale = 3/4
NUM_STATES = 7*7*512+his_actions*NUM_ACTIONS

In [23]:

def init_process(image, transform=None):
    # image.show()
    # time.sleep(5)
    if transform:
        image = transform(image)
    return image.unsqueeze(0)


def inter_process(image, bbx, transform=None):
    (left, upper, right, lower) = (bbx[0], bbx[2], bbx[1], bbx[3])
    image_crop = image.crop((left, upper, right, lower))
    # image_crop.show()
    # time.sleep(5)
    if transform:
        image_crop = transform(image_crop)
    return image_crop.unsqueeze(0)


def update_bbx(bbx, action):
    new_bbx = np.zeros(4)
    if action == 0:  # top left
        new_bbx[0] = bbx[0]  # x1
        new_bbx[1] = bbx[0] + (bbx[1]-bbx[0]) * subscale  # x2
        new_bbx[2] = bbx[2]  # y1
        new_bbx[3] = bbx[2] + (bbx[3]-bbx[2]) * subscale  # y2
    elif action == 1:  # top right
        new_bbx[0] = bbx[1] - (bbx[1]-bbx[0]) * subscale  # x1
        new_bbx[1] = bbx[1]  # x2
        new_bbx[2] = bbx[2]  # y1
        new_bbx[3] = bbx[2] + (bbx[3]-bbx[2]) * subscale  # y2
    elif action == 2:  # lower left
        new_bbx[0] = bbx[0]  # x1
        new_bbx[1] = bbx[0] + (bbx[1]-bbx[0]) * subscale  # x2
        new_bbx[2] = bbx[3] - (bbx[3]-bbx[2]) * subscale  # y1
        new_bbx[3] = bbx[3]  # y2
    elif action == 3:  # lower right
        new_bbx[0] = bbx[1] - (bbx[1]-bbx[0]) * subscale  # x1
        new_bbx[1] = bbx[1]  # x2
        new_bbx[2] = bbx[3] - (bbx[3]-bbx[2]) * subscale  # y1
        new_bbx[3] = bbx[3]  # y2
    elif action == 4:  # center
        new_bbx[0] = (bbx[0]+bbx[1])/2-(bbx[1]-bbx[0]) * subscale/2  # x1
        new_bbx[1] = (bbx[0]+bbx[1])/2+(bbx[1]-bbx[0]) * subscale/2  # x2
        new_bbx[2] = (bbx[2]+bbx[3])/2-(bbx[3]-bbx[2]) * subscale/2  # y1
        new_bbx[3] = (bbx[2]+bbx[3])/2+(bbx[3]-bbx[2]) * subscale/2  # y2
    elif action == 5:
        new_bbx = bbx
    return new_bbx

# def update_bbx(bbx, action):
#     new_bbx = np.zeros(4)
#     if action == 0:  # left
#         new_bbx[0] = bbx[0]  # x1
#         new_bbx[1] = bbx[0] + (bbx[1]-bbx[0]) * subscale  # x2
#         new_bbx[2] = bbx[2]  # y1
#         new_bbx[3] = bbx[3] #+ (bbx[3]-bbx[2]) * subscale  # y2
#     elif action == 1:  # right
#         new_bbx[0] = bbx[1] - (bbx[1]-bbx[0]) * subscale  # x1
#         new_bbx[1] = bbx[1]  # x2
#         new_bbx[2] = bbx[2]  # y1
#         new_bbx[3] = bbx[3] # + (bbx[3]-bbx[2]) * subscale  # y2
#     elif action == 2:  # bot 
#         new_bbx[0] = bbx[0]  # x1
#         new_bbx[1] = bbx[1] #+ (bbx[1]-bbx[0]) * subscale  # x2
#         new_bbx[2] = bbx[3] - (bbx[3]-bbx[2]) * subscale  # y1
#         new_bbx[3] = bbx[3]  # y2
#     elif action == 3:  # top
#         new_bbx[0] = bbx[0]  #- (bbx[1]-bbx[0]) * subscale  # x1
#         new_bbx[1] = bbx[1]  # x2
#         new_bbx[2] = bbx[2]  # y1
#         new_bbx[3] = bbx[2] + (bbx[3]-bbx[2]) * subscale  # y2
#     elif action == 4:  # center
#         new_bbx[0] = (bbx[0]+bbx[1])/2-(bbx[1]-bbx[0]) * subscale/2  # x1
#         new_bbx[1] = (bbx[0]+bbx[1])/2+(bbx[1]-bbx[0]) * subscale/2  # x2
#         new_bbx[2] = (bbx[2]+bbx[3])/2-(bbx[3]-bbx[2]) * subscale/2  # y1
#         new_bbx[3] = (bbx[2]+bbx[3])/2+(bbx[3]-bbx[2]) * subscale/2  # y2
#     elif action == 5:
#         new_bbx = bbx
#     return new_bbx


In [10]:
trans = T.Compose([
        T.Resize((224, 224)),
        T.ToTensor(),
    ])

In [11]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [15]:
feature_exactrator = torchvision.models.vgg16(
        pretrained=True).features.to(device)

c:\Users\21520\anaconda3\.conda\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\21520\anaconda3\.conda\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [37]:
class DQN():
    """docstring for DQN"""

    def __init__(self, device):
        super().__init__()
        self.device = device
        self.eval_net, self.target_net = Q_zoom(), Q_zoom()
        self.eval_net.to(self.device)
        self.target_net.to(self.device)
        self.learn_step_counter = 0
        self.memory_counter = 0
        self.memory = np.zeros((MEMORY_CAPACITY, NUM_STATES * 2 + 2))
        # why the NUM_STATE*2 +2
        # When we store the memory, we put the state, action, reward and next_state in the memory
        # here reward and action is a number, state is a ndarray
        self.optimizer = torch.optim.Adam(self.eval_net.parameters(), lr=LR)
        self.loss_func = nn.MSELoss()

    def choose_action(self, state, EPISILO):
        state = torch.unsqueeze(torch.FloatTensor(state), 0).to(
            self.device)  # get a 1D array
        if np.random.randn() <= EPISILO:  # random policy
            action = np.random.randint(0, NUM_ACTIONS-1)
        else:  # greedy policy
            action_value = self.eval_net.forward(state)
            action = torch.max(action_value, 1)[1].cpu().item()
        return action

    def store_transition(self, state, action, reward, next_state):
        transition = np.hstack((state, [action, reward], next_state))
        index = self.memory_counter % MEMORY_CAPACITY
        self.memory[index, :] = transition
        self.memory_counter += 1

    def learn(self):

        # update the parameters
        if self.learn_step_counter % Q_NETWORK_ITERATION == 0:
            self.target_net.load_state_dict(self.eval_net.state_dict())
        self.learn_step_counter += 1

        # sample batch from memory
        sample_index = np.random.choice(MEMORY_CAPACITY, BATCH_SIZE)
        batch_memory = self.memory[sample_index, :]
        batch_state = torch.FloatTensor(
            batch_memory[:, :NUM_STATES]).to(self.device)
        batch_action = torch.LongTensor(
            batch_memory[:, NUM_STATES:NUM_STATES+1].astype(int)).to(self.device)
        batch_reward = torch.FloatTensor(
            batch_memory[:, NUM_STATES+1:NUM_STATES+2]).to(self.device)
        batch_next_state = torch.FloatTensor(
            batch_memory[:, -NUM_STATES:]).to(self.device)

        # q_eval
        q_eval = self.eval_net(batch_state).gather(1, batch_action)
        q_next = self.target_net(batch_next_state).detach()
        q_target_unterminated = batch_reward + GAMMA * \
            q_next.max(1)[0].view(BATCH_SIZE, 1)
        q_target = torch.where(
            batch_action != 5, q_target_unterminated, batch_reward)
        loss = self.loss_func(q_eval, q_target)
        print("step loss is {:.3f}".format(loss.cpu().detach().item()))

        self.optimizer.zero_grad()
        loss.backward()
        self.optimizer.step()
    def load_eval_net(self, filepath):
        # Load the model state dict with the correct device mapping
        state_dict = torch.load(filepath, map_location=self.device)
        self.eval_net.load_state_dict(state_dict)
        self.eval_net.to(self.device)

In [54]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
dqn = DQN(device)
dqn.load_eval_net("eval_net.pth")

In [26]:
EPISILO = -100

In [27]:
path_voc = r"e:\msrlOB-1\archive (4)\VOCtrainval_06-Nov-2007\VOC2007"

In [46]:
    # calculate the average IOU over test set
    image_names = np.array(load_images_names_in_data_set(
        'aeroplane_train', path_voc))
    single_plane_image_names = []
    single_plane_image_gts = []
    for image_name in image_names:
        annotation = get_bb_of_gt_from_pascal_xml_annotation(
            image_name, path_voc)
        #if (len(annotation) > 1):
        #    continue
        single_plane_image_names.append(image_name)
        single_plane_image_gts.append(annotation[0][1:])  # [[x1,x2,y1,y2] ...

    # save single_plane_image_names and single_plane_image_gts for future use
    np.save('single_plane_image_names_train.npy', single_plane_image_names)
    np.save('single_plane_image_gts_train.npy', single_plane_image_gts)

In [50]:
    # calculate the average IOU over test set
    image_names = np.array(load_images_names_in_data_set(
        'aeroplane_test', path_voc_test))
    single_plane_image_names = []
    single_plane_image_gts = []
    for image_name in image_names:
        annotation = get_bb_of_gt_from_pascal_xml_annotation(
            image_name, path_voc_test)
        #if (len(annotation) > 1):
        #    continue
        single_plane_image_names.append(image_name)
        single_plane_image_gts.append(annotation[0][1:])  # [[x1,x2,y1,y2] ...

    # save single_plane_image_names and single_plane_image_gts for future use
    np.save('single_plane_image_names.npy', single_plane_image_names)
    np.save('single_plane_image_gts.npy', single_plane_image_gts)

In [52]:
    single_plane_image_names= np.load('single_plane_image_names_train.npy')
    single_plane_image_gts= np.load('single_plane_image_gts_train.npy')
    print("single_plane_image_names and single_plane_image_gts saved")
    # print out the average IOU
    total_iou = 0
    for index, image_name in enumerate(single_plane_image_names):
        image_path = os.path.join(
            path_voc + "\JPEGImages", image_name + ".jpg")
        image_original = Image.open(image_path)
        width, height = image_original.size
        bbx_gt = single_plane_image_gts[index]

        image = init_process(image_original, trans).to(device)
        bbx = [0, width, 0, height]
        history_action = np.zeros(his_actions*NUM_ACTIONS)
        with torch.no_grad():
            vector = feature_exactrator(
                image).cpu().detach().numpy().reshape(7*7*512)
        state = np.concatenate([history_action, vector])
        step = 0
        #ma_iou =  float("-inf")
        while (step < 10):
            iou = cal_iou(bbx, bbx_gt)
            #ma_iou = max(ma_iou, iou)
            if iou > 0.4:
                action = 5
            else:
                action = dqn.choose_action(state, EPISILO)
            new_bbx = update_bbx(bbx, action)
            if action == 5:
                break
            state = np.concatenate([history_action, vector])
            bbx = new_bbx
            step += 1
        annotations = get_bb_of_gt_from_pascal_xml_annotation(image_name, path_voc)
        ma_iou = 0
        for i in range(len(annotations)):
            cur_bbx = annotations[i][1:]
            ma_iou = max(ma_iou, cal_iou(bbx, cur_bbx))
        total_iou += ma_iou
        #total_iou += cal_iou(bbx, bbx_gt)
        #total_iou += ma_iou
        # write out bbx, bbx_gt to file
        with open('bbx.txt', 'a') as f:
            f.write("bbx: {}, bbx_gt: {}\n".format(bbx, bbx_gt))
    print("average IOU is {:.3f}".format(
        total_iou/len(single_plane_image_names)))

single_plane_image_names and single_plane_image_gts saved
average IOU is 0.402


In [55]:
    single_plane_image_names= np.load('single_plane_image_names.npy')
    single_plane_image_gts= np.load('single_plane_image_gts.npy')
    print("single_plane_image_names and single_plane_image_gts saved")
    # print out the average IOU
    total_iou = 0
    for index, image_name in enumerate(single_plane_image_names):
        image_path = os.path.join(
            path_voc_test + "\JPEGImages", image_name + ".jpg")
        image_original = Image.open(image_path)
        width, height = image_original.size
        bbx_gt = single_plane_image_gts[index]

        image = init_process(image_original, trans).to(device)
        bbx = [0, width, 0, height]
        history_action = np.zeros(his_actions*NUM_ACTIONS)
        with torch.no_grad():
            vector = feature_exactrator(
                image).cpu().detach().numpy().reshape(7*7*512)
        state = np.concatenate([history_action, vector])
        step = 0
        #ma_iou =  float("-inf")
        while (step < 10):
            iou = cal_iou(bbx, bbx_gt)
            #ma_iou = max(ma_iou, iou)
            if iou > 0.4:
                action = 5
            else:
                action = dqn.choose_action(state, EPISILO)
            new_bbx = update_bbx(bbx, action)
            if action == 5:
                break
            state = np.concatenate([history_action, vector])
            bbx = new_bbx
            step += 1
        annotations = get_bb_of_gt_from_pascal_xml_annotation(image_name, path_voc_test)
        ma_iou = 0
        for i in range(len(annotations)):
            cur_bbx = annotations[i][1:]
            ma_iou = max(ma_iou, cal_iou(bbx, cur_bbx))
        total_iou += ma_iou
        #total_iou += cal_iou(bbx, bbx_gt)
        #total_iou += ma_iou
        # write out bbx, bbx_gt to file
        with open('bbx.txt', 'a') as f:
            f.write("bbx: {}, bbx_gt: {}\n".format(bbx, bbx_gt))
    print("average IOU is {:.3f}".format(
        total_iou/len(single_plane_image_names)))

single_plane_image_names and single_plane_image_gts saved


In [22]:
import os
from PIL import Image

image_path = 'E:\\msrlOB-1\\archive (4)\\VOCtest_06-Nov-2007\\VOC2007\\JPEGImages\\001373.jpg'

if os.path.exists(image_path):
    print(1)
else:
    print(f"File not found: {image_path}")

1
